// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCQbaeqQsq5wECYN_VgIHPSo5Tmzs8WE0',
    appId: '1:993049949961:web:e100482e73cb69e2ca85d8',
    messagingSenderId: '993049949961',
    projectId: 'the-sip-spot',
    authDomain: 'the-sip-spot.firebaseapp.com',
    storageBucket: 'the-sip-spot.firebasestorage.app',
    measurementId: 'G-8ZKEEQFN19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpeK6OAUUfsaA79vccotMwhf1JbXWAses',
    appId: '1:993049949961:android:5ecb6f398681d855ca85d8',
    messagingSenderId: '993049949961',
    projectId: 'the-sip-spot',
    storageBucket: 'the-sip-spot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD_paBa4PMNX5Dhy_t14wHW4eHadhMS0w',
    appId: '1:993049949961:ios:c25228fa49c30576ca85d8',
    messagingSenderId: '993049949961',
    projectId: 'the-sip-spot',
    storageBucket: 'the-sip-spot.firebasestorage.app',
    iosBundleId: 'com.example.sipSpot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD_paBa4PMNX5Dhy_t14wHW4eHadhMS0w',
    appId: '1:993049949961:ios:c25228fa49c30576ca85d8',
    messagingSenderId: '993049949961',
    projectId: 'the-sip-spot',
    storageBucket: 'the-sip-spot.firebasestorage.app',
    iosBundleId: 'com.example.sipSpot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCQbaeqQsq5wECYN_VgIHPSo5Tmzs8WE0',
    appId: '1:993049949961:web:a55d6c81c3066337ca85d8',
    messagingSenderId: '993049949961',
    projectId: 'the-sip-spot',
    authDomain: 'the-sip-spot.firebaseapp.com',
    storageBucket: 'the-sip-spot.firebasestorage.app',
    measurementId: 'G-C07TPDNKH1',
  );
}
